---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-pubsub
  labels:
    app: goapp-pubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp-pubsub
  template:
    metadata:
      labels:
        app: goapp-pubsub
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "bla"
        dapr.io/port: "3000"
        dapr.io/log-level: "debug"
    spec:
      containers:
        - name:  goapp-pubsub
          image: ko://github.com/nachtmaar/dapr-eventhubs-bindings/pubsub
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: APP_PORT
              value: "3000"
